# Generated by Django 4.1.7 on 2023-08-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearance', '0002_remove_student_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
