# Generated by Django 4.2.1 on 2023-08-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearance', '0003_alter_student_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date_paid']},
        ),
        migrations.AddField(
            model_name='fee',
            name='category',
            field=models.CharField(default='tuition', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='category',
            field=models.CharField(default='tuition', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fee',
            name='department',
            field=models.CharField(default='Tuition', max_length=100),
        ),
    ]
